pull_request_rules:
  - name: automatically merge scala-steward's PRs
    conditions:
      - author=scala-steward
      - body~=labels:.*semver-patch.*
      - status-success=Build and Test (ubuntu-latest, 2.13.10, temurin@17)
    actions:
      merge:
        method: merge
