addSbtPlugin("org.typelevel"  % "sbt-tpolecat"        % "0.5.0")
addSbtPlugin("io.spray"       % "sbt-revolver"        % "0.10.0")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.11.0")
addSbtPlugin("com.codecommit" % "sbt-github-actions"  % "0.14.2")
